config/routes.rb
Markymark::Application.routes.draw do

  root to: 'home#index'

  resources :users, only: [ :show, :edit, :update ]

  get '/auth/:provider/callback' => 'sessions#create'
  get '/login/:provider' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  get '/auth/failure' => 'sessions#failure'

  resources :links do
    member do
      get 'refresh' => 'links#refresh', as: 'refresh'
    end
  end

  get '/tags' => 'links#tags', as: 'tags'
  get '/links/tags/:tag' => 'links#index', as: 'tagged_links'
  get '/links/domains/(:site)' => 'links#index', as: 'domain_links', constraints: { site: /[^\/]+/ }

  resources :classifications, only: [ :index, :new, :create, :show, :update ] do
    collection do
      post 'classify' => 'classifications#classify', as: 'classify'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :links
  has_many :identities, dependent: :destroy

  validates_presence_of :name

  class << self

    def find_or_create_with_omniauth(identity, auth)
      user = User.find_by_email(auth['info']['email'])
      user.nil? ? create_with_omniauth(identity, auth) : user
    end

    def create_with_omniauth(identity, auth)
      u = create! do |user|
        if auth['info']
           user.name = auth['info']['name'] || ""
           user.email = auth['info']['email'] || ""
        end
      end
      u.tap do |user|
        if user.persisted?
          identity.update_attributes(user_id: user.id)
          HarvestLinksWorker.perform_async(user.id, identity.provider_id)
        end
      end
    end
  end

  def token(options = {})
    raise ArgumentError unless identity = identities.where(provider_id: options[:provider_id]).first
    identity.token
  end

  def secret(options = {})
    raise ArgumentError unless identity = identities.where(provider_id: options[:provider_id]).first
    identity.secret
  end

  def username(options = {})
    raise ArgumentError unless identity = identities.where(provider_id: options[:provider_id]).first
    identity.username
  end

  def disconnected_providers
    Provider.all - connected_providers
  end

  def connected_providers
    identities.map(&:provider)
  end

  def connected_facebook?
    identities.facebook.any?
  end

  def connected_twitter?
    identities.twitter.any?
  end

  def connected_pocket?
    identities.pocket.any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end

  def update
    @user = User.find(params[:id])

    redirect_to root_path unless @user == current_user

    if @user.update_attributes(secure_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end

  private

  def secure_params
    params.require(:user).permit(:email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Update"

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
.user

  %h3= @user.name

  .providers

    - if @user.connected_providers.any?

      %h6 Connected
      %ul.connected-providers.list-group
        - @user.connected_providers.each do |provider|
          %li.connected-provider.list-group-item
            %span.provider-icon{class: "fui-#{provider.name}"}
            = provider.name
            %span.fui-check.pull-right

    - if @user.disconnected_providers.any?

      %h6 Disconnected
      %ul.disconnected-providers.list-group
        - @user.disconnected_providers.each do |provider|
          %li.disconnected-provider.list-group-item
            %span.provider-icon{class: "fui-#{provider.name}"}
            = link_to provider.name, login_path(provider: provider.slug)
            %span.fui-cross.pull-right

  = link_to 'Edit account', edit_user_path(@user)