config/routes.rb
Markymark::Application.routes.draw do

  root to: 'home#index'

  resources :users, only: [ :show, :edit, :update ]

  get '/auth/:provider/callback' => 'sessions#create'
  get '/login/:provider' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  get '/auth/failure' => 'sessions#failure'

  resources :links do
    member do
      get 'refresh' => 'links#refresh', as: 'refresh'
    end
  end

  get '/tags' => 'links#tags', as: 'tags'
  get '/links/tags/:tag' => 'links#index', as: 'tagged_links'
  get '/links/domains/(:site)' => 'links#index', as: 'domain_links', constraints: { site: /[^\/]+/ }

  resources :classifications, only: [ :index, :new, :create, :show, :update ] do
    collection do
      post 'classify' => 'classifications#classify', as: 'classify'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/link.rb
# encoding: UTF-8

class Link < ActiveRecord::Base

  belongs_to :user
  belongs_to :provider

  validates :url, presence: true, uniqueness: { scope: :user_id }
  validates :title, presence: true, if: Proc.new { |l| l.scraped? }
  # validate :worthy, if: Proc.new { |l| l.scraped? }

  scope :facebook, -> { where(provider_id: Provider.facebook.id) }
  scope :twitter, -> { where(provider_id: Provider.twitter.id) }
  scope :pocket, -> { where(provider_id: Provider.pocket.id) }
  scope :scraped, -> { where(scraped: true) }

  attr_taggable :tags

  self.per_page = 50

  class << self

    def process(url, title, posted_at, provider_id, user_id)
      link = Link.new(
        url: url,
        title: title,
        posted_at: posted_at,
        provider_id: provider_id,
        user_id: user_id
      )
      link.save_metadata
    rescue => e
      puts "Link.process: #{e.class}: #{e.message}".white_on_black
      false
    end

    def scrape(user_id, provider_id)
      Link.where(user_id: user_id, provider_id: provider_id, scraped: false).
        order('posted_at DESC').pluck(:id).in_groups_of(33).each_with_index do |group, i|
          ScrapeLinkGroupWorker.perform_at(i.minutes.from_now, group)
      end
    end
  end

  def refresh
    save_metadata
  end

  def save_metadata
    if fetch_metadata
      self.scraped = true
      save
    end
  end

  def is_image?
    url.match(/\.(png|jpg|gif)$/).present?
  end

  def sample
    if content && content.length > description.length
      content
    elsif description && description.length > 10
      description
    elsif title && title.length > 10
      title
    elsif tags.any?
      tags.join(", ")
    else
      domain
    end
  end

  private

  def queue_metadata_worker
    UpdateLinksWorker.perform_async(self.id)
  end

  def fetch_metadata
    begin
      meta_inspector_page = MetaInspector.new(self.url, timeout: 30, allow_redirections: :all, warn_level: :warn)
      pismo_page = Pismo::Document.new(self.url)

      self.url = (meta_inspector_page.meta['og:url'] || meta_inspector_page.url) rescue self.url
      self.domain = meta_inspector_page.host.gsub('www.', '') rescue Addressable::URI.parse(self.url).host.gsub('www.', '')
      self.title = (pismo_page.title || meta_inspector_page.title) rescue self.title
      self.lede = pismo_page.lede rescue self.lede
      self.description = (meta_inspector_page.description || pismo_page.description) rescue self.description
      self.image_url = meta_inspector_page.image rescue self.image_url
      self.content = pismo_page.body rescue self.content
      self.html_content = pismo_page.html_body rescue self.html_content
      self.content_links = meta_inspector_page.links rescue self.content_links
      self.tags << pismo_page.keywords.first(5).map(&:first) rescue self.tags
      true
    rescue => e
      puts "Link#fetch_metadata: #{e.class}: #{e.message}".red_on_white
      false
    end
  end

  def worthy
    unless domain.present? || description.present? || lede.present? || image_url.present?
      errors.add(:base, 'Link is not worthy.')
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :set_link, only: [:show, :refresh]

  def index
    if params[:tag]
      links = Link.tagged_with(params[:tag]).where(user_id: current_user.id)
    elsif params[:site]
      links = current_user.links.where(domain: params[:site])
    else
      links = current_user.links
    end
    @links = links.page(params[:page]).order('posted_at DESC')
  end

  def new
    @link = current_user.links.build
  end

  def create
    @link = current_user.links.build(link_params.merge(posted_at: Time.now))

    if @link.save
      redirect_to links_path
    else
      render :new
    end
  end

  def show
  end

  def tags
    @tags = RocketTag::Tag.where('lower(name) like ?', "%#{params[:q].downcase}%").limit(100)
  end

  def refresh
    @link.refresh
    redirect_to classifications_path(link_id: @link.id)
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:title, :description, :url, :image_url, :content, :domain, :posted_at)
  end
end

app/views/links/_link.html.haml
= content_tag_for :li, link, class: "media #{domain_class_name(link)}", data: { id: link.id } do

  - if link.image_url

    = link_to image_tag(link.image_url, class: 'media-object img-rounded img-responsive img-64x64', alt: link.title), link.url, class: 'pull-left link-image'

  - else

    .pull-left.link-image
      .img-placeholder.img-64x64

  .media-body

    %h6.media-heading
      - if link.domain.present?
        = link_to link.domain, domain_links_path(link.domain), class: 'domain'

      = embeddable_type(link) if embeddable?(link)
      = link_to link.title.try(:html_safe), link.url, target: '_blank', class: 'title'

    %p.description
      - if link.description.present?
        = truncate(link.description, length: 140, separator: ' ').html_safe
      - elsif link.lede.present?
        = truncate(link.lede, length: 140, separator: ' ').html_safe

    = embed(link)

    - if link.tags.any?
      .tags
        - link.tags.first(5).each do |tag|
          = link_to tag, tagged_links_path("#{tag}"), class: 'tag label label-default'

    -# %p.posted-at= link.posted_at.to_formatted_s

app/views/links/index.html.haml
- content_for :list_menu do

  %h3 Links

- content_for :list do

  - if @links.any?

    %ul.links.media-list
      = render @links

    .pagination-wrapper.text-center.clearfix
      = will_paginate @links, previous_label: '&laquo;', next_label: '&raquo;'
      .page-entries-info= page_entries_info @links

  - else

    %h6 There are no links yet.

app/views/links/new.html.haml
- content_for :main do

  = simple_form_for Link.new do |f|

    = f.input :url

    = f.submit

app/views/links/show.html.haml
- content_for :main do

  .link{ id: "link_#{@link.id}" }

    %h3.title
      = link_to @link.title, @link.url, target: '_blank'

    - if @link.html_content.present?
      .html-content= @link.html_content.html_safe
    - else
      .content= @link.content

app/views/links/tags.html.haml
.tags
  - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
    = link_to tag.name, tagged_links_path(tag.name), class: css_class