config/routes.rb
Markymark::Application.routes.draw do

  root to: 'home#index'

  resources :users, only: [ :show, :edit, :update ]

  get '/auth/:provider/callback' => 'sessions#create'
  get '/login/:provider' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  get '/auth/failure' => 'sessions#failure'

  resources :links do
    member do
      get 'refresh' => 'links#refresh', as: 'refresh'
    end
  end

  get '/tags' => 'links#tags', as: 'tags'
  get '/links/tags/:tag' => 'links#index', as: 'tagged_links'
  get '/links/domains/(:site)' => 'links#index', as: 'domain_links', constraints: { site: /[^\/]+/ }

  resources :classifications, only: [ :index, :new, :create, :show, :update ] do
    collection do
      post 'classify' => 'classifications#classify', as: 'classify'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/classification.rb
class Classification < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { scope: :content_type }

  class << self

    def seed
      StructuralClassification.seed
      TopicalClassification.seed
    end
  end
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController

  before_action :set_classification, only: [:show]

  def index
    @sample = params[:link_id] ? Link.find(params[:link_id]) : Link.order_by_rand.first
  end

  def new
    @classification = Classification.new
  end

  def create
    @classification = Classification.new(classification_params)

    if @classification.save
      redirect_to classifications_path
    else
      render :new
    end
  end

  def show
  end

  def update
  end

  def classify
    @structural_classification = StructuralClassification.find(classification_params[:structural_classification_id])
    @link = Link.find(classification_params[:link_id])
    @link.tags << classification_params[:tags].split(',')
    @link.save
    @trainer = Trainer.new(category: @structural_classification.name, sample: @link.sample)
    @trainer.classify
    redirect_to classifications_path
  end

  private

  def set_classification
    @classification = Classification.find(params[:id])
  end

  def classification_params
    params.require(:classification).permit(:id, :structural_classification_id, :name, :description, :content_type, :link_id, :tags)
  end
end

app/views/classifications/index.html.haml
- content_for :list_menu do

  %h3 Classifications

- content_for :main do

  = simple_form_for :classification, url: classify_classifications_url do |f|

    %legend Classifier

    - if @sample.present?

      .link{ id: "link_#{@sample.id}" }

        %h3.title
          = link_to @sample.title.try(:html_safe), @sample.url, target: '_blank'

        - if @sample.description
          .description.attribute-block
            %h4 Description
            %p= @sample.description

        - if @sample.html_content.present?
          .html-content.attribute-block
            %h4 HTML Content
            = @sample.html_content.html_safe

        - elsif @sample.content.present?
          .content.attribute-block
            %h4 Content
            = @sample.content

      = f.hidden_field :link_id, value: @sample.id
    
    = f.input :structural_classification_id, as: :grouped_collection_select, collection: Classification.all.group_by(&:content_type), group_method: :last, label: false, input_html: { class: 'select2 input-lg', 'data-placeholder' => 'What kind of document is this?' }

    = f.input :tags, label: false, input_html: { class: 'select2-ajax input-lg', data: { url: tags_url, multiple: true, placeholder: 'What kind of content is this?' } }

    = f.button :submit, 'Save', class: 'btn-primary btn-block btn-lg'

    = link_to 'Refresh Link', refresh_link_path(@sample), class: 'btn btn-default btn-block btn-lg'