config/routes.rb
Markymark::Application.routes.draw do

  root to: 'home#index'

  resources :users, only: [ :show, :edit, :update ]

  get '/auth/:provider/callback' => 'sessions#create'
  get '/login/:provider' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  get '/auth/failure' => 'sessions#failure'

  resources :links do
    member do
      get 'refresh' => 'links#refresh', as: 'refresh'
    end
  end

  get '/tags' => 'links#tags', as: 'tags'
  get '/links/tags/:tag' => 'links#index', as: 'tagged_links'
  get '/links/domains/(:site)' => 'links#index', as: 'domain_links', constraints: { site: /[^\/]+/ }

  resources :classifications, only: [ :index, :new, :create, :show, :update ] do
    collection do
      post 'classify' => 'classifications#classify', as: 'classify'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_list.html.haml
#list.col-xs-3.col-xs-height.col-top.layout-col
  .menu= yield :list_menu
  .content.rendered.clearfix= yield :list

app/views/layouts/_main.html.haml
#main.col-xs-7.col-xs-height.col-top.layout-col
  .menu= yield :main_menu
  .content.rendered.clearfix
    .inner= yield :main

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-lg{role: "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target" => "#navbar_collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
    = link_to 'MarkyMarks', root_path, class: 'navbar-brand'
  #navbar_collapse.collapse.navbar-collapse
    %ul.nav.navbar-nav
      = render 'layouts/navigation_links'
    = render 'layouts/navigation_dropdown' if current_user

app/views/layouts/_navigation_dropdown.html.haml
%ul.nav.navbar-nav.navbar-right
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      = current_user.name
      %b.caret
    %span.dropdown-arrow
    %ul.dropdown-menu
      %li= link_to 'Profile', user_path(current_user)
      - unless current_user.connected_facebook?
        %li= link_to 'Connect Facebook', login_path(provider: 'facebook')
      - unless current_user.connected_twitter?
        %li= link_to 'Connect Twitter', login_path(provider: 'twitter')
      - unless current_user.connected_pocket?
        %li= link_to 'Connect Pocket', login_path(provider: 'pocket')
      %li= link_to 'Logout', logout_path

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Home', root_path

- if signed_in?

  %li= link_to 'Links', links_path

- else

  %ul.nav.navbar-nav.navbar-right
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
        Login
        %b.caret
      %span.dropdown-arrow
      %ul.dropdown-menu
        %li= link_to 'Facebook', login_path(provider: 'facebook')
        %li= link_to 'Twitter', login_path(provider: 'twitter')
        %li= link_to 'Pocket', login_path(provider: 'pocket')

app/views/layouts/_sidebar.html.haml
#sidebar.col-xs-2.col-xs-height.col-top.layout-col
  .menu
    = yield :sidebar_menu
  .content.rendered.clearfix
    %ul.nav.nav-stacked
      - if current_user
        %li= link_to 'Home', root_path
        %li= link_to 'Links', links_path
        %li= link_to 'Trainer', classifications_path
        %li.divider
        %li= link_to 'Logout', logout_path
    = yield :sidebar

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'MarkyMarks'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Markymark'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid.container-xs-height
      .row.row-xs-height
        = render 'layouts/sidebar'
        = render 'layouts/list'
        = render 'layouts/main'